flowchart TB
    MS1["map: group='PF14'"] --> C2["get_group_name → i"]
    MS2["map: function='af5'"] --> C1["get_function_name → 6"]
    C2 --> SN1["setting.group = i"]
    C1 --> SN2["setting.func = 6"]
